Repository fortytwoservices/terraform-azurerm-selfhostedrunnervmss, pull requests merged in 2024-08, with the labels that each got.

#164 Feat: added vmss identity service principal output
  README.md
  outputs.tf
Labels: enhancement

#165 Feat: added conditional identity blocks to vmss resources and optional input
  README.md
  _README_header.md
  examples/advanced/main.tf
  examples/basic/main.tf
  main.tf
  terraform.tf
  variables.tf
Labels: enhancement

#163 chore(main): release 1.7.0
  .release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending

#167 fix: fixed value reference for identity principal id output
  outputs.tf
Labels: bug

#170 chore(main): release 1.7.2
  .release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending
